services:
  frontend:
    image: node:alpine
    container_name: frontend
    # entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    command: npm run dev && docker logs -f frontend
